### ISSUE TITLE
if hexo-config support get attr from site config file

### ISSUE THREAD

**Issue by cbvar** [hexojs/hexo-renderer-stylus#11]
When i call hexo-config('root') from styl file, it return empty because theme lack of 'root' attr.  So i think that if hexo-config shoud support get attr from site config file again, or how to handle the root problem?

**Comment by cbas** [comment]
@cbvar I just faced the same problem. It looks like we have to use the theme configuration (`/themes/your-theme-name/_config.yml`) instead of the main Hexo configuration file (`/_config.yml`).

@tommy351 Would it not make sense to allow looking up in the main configuration properties? Maybe as a fallback, so it would not break existing themes. My use case is to read the `url` and `root` properties to generate absolute URLs in CSS.

**Comment by kgraves** [comment]
I also just ran into needing this for a Hexo project. Only the theme's config is available through `hexo-config`, but I want to be able to customize my site through settings in my config file. To be backwards compatible like @cbas suggested, something like the following might suffice:

```javascript
style.define('hexo-site-config', function(data) {
  return getProperty(self.config, data.val);
});
```

**Comment by tomap** [comment]
Those lines seem to solve this question:
https://github.com/hexojs/hexo-renderer-stylus/blob/master/lib/renderer.js#L5

doesn't it?

**Comment by stevenjoezhang** [comment]
Use `theme_config`

https://github.com/hexojs/hexo-renderer-stylus/pull/41
