### ISSUE TITLE
block in lib/renderer.js

### ISSUE THREAD

**Issue by ftsqh** [hexojs/hexo-renderer-stylus#5]
I can't GET css/style.css when I use hexo@2.8.2, and I check the code found it block at hexo-renderer-stylus/lib/renderer.js:18&19, the code is `var config = this.config.stylus || {}; var self = this.hexo;`, it work s after I change `this` to `this.hexo`

**Comment by juanyao** [comment]
@ftsqh I met the same problem too using hexo@2.8.3, and solved after making the change as you mentioned. The problem is that when I `hexo generate`, it doesn't generate any layout related files, and the output is not consistent (extra font files sometimes). 

Was about to give up on hexo as this is my first time using it and can't get it to work at all. Luckily I stumbled into your post. Thanks a lot!

**Comment by tommy351** [comment]
Sorry! 0.2.0 is for Hexo 3.0. Please install the old version instead.

``` bash
$ npm install hexo-renderer-stylus@0.1 --save
```

**Comment by juanyao** [comment]
@tommy351 Ok. Should the package.json of hexo be changed accordingly?

`
{
  "name": "hexo-site",
  "version": "2.8.3",
  "private": true,
  "dependencies": {
    "hexo-renderer-ejs": "*",
    "hexo-renderer-stylus": "*",
    "hexo-renderer-marked": "*"
  }
}
`

**Comment by shunia** [comment]
@tommy351 @juanyao 修改package.json中的stylus版本为0.1,然后在目录里npm install好像就对了.老大说的直接--save的方式应该也要在目录里运行,我刚直接给装到外边去了...

**Comment by juanyao** [comment]
@shunia 。对，修改了就可以了。
